### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/upload#3]
Hi there ForumHulp,

I'm getting on 3.2.1 some errors after upgrading from 3.1:

[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/upload/includes/extensions_list.php on line 157: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_acp.php on line 137: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3262)

I'm using too PHP 7.0.26

**Comment by ForumHulp** [comment]
You probably didn't get a answer from phpbb.com

**Comment by Leinad4Mind** [comment]
I didnt ask to them, since I saw this on this extension. But why are you saying that?

**Comment by ForumHulp** [comment]
Ooh sorry didn't saw your second question. 
I meant the extension is asking data at phpbb.com and their server didn't respond.
