### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by ashishpatel1992** [ForumHulp/upload#4]
I am having following error while opening **upload extension** plugin

`Catchable fatal error: Object of class phpbb\config\db could not be converted to string in /home/admin/public_html/mysite/phpbb/extension/metadata_manager.php on line 49`

Have also tried disabling all extension but nothing seem to help.

**Comment by ForumHulp** [comment]
Provide more info as I can not reproduce this

**Comment by ashishpatel1992** [comment]
Got it fixed. uploaded in wrong directory.
